"""Public error types and stable error metadata for ansiblectl integrations."""

from ansiblectl.domain.errors import (
    ERROR_CODE_REGISTRY,
    AnsiblectlError,
    AuthenticationError,
    ConfigurationError,
    ConflictError,
    ErrorCode,
    ErrorDefinition,
    ExecutionError,
    ExitCode,
    ExternalToolError,
    FilesystemCapabilityError,
    FilesystemRecoveryError,
    FilesystemTransactionError,
    InfrastructureError,
    InternalOperationalError,
    InventoryError,
    MigrationError,
    NotFoundError,
    OperationCancelledError,
    PermissionDeniedError,
    PluginError,
    RepositoryError,
    SecretsError,
    UsageError,
    ValidationError,
)

__all__ = [
    "ERROR_CODE_REGISTRY",
    "AnsiblectlError",
    "AuthenticationError",
    "ConfigurationError",
    "ConflictError",
    "ErrorCode",
    "ErrorDefinition",
    "ExecutionError",
    "ExitCode",
    "ExternalToolError",
    "FilesystemCapabilityError",
    "FilesystemRecoveryError",
    "FilesystemTransactionError",
    "InfrastructureError",
    "InternalOperationalError",
    "InventoryError",
    "MigrationError",
    "NotFoundError",
    "OperationCancelledError",
    "PermissionDeniedError",
    "PluginError",
    "RepositoryError",
    "SecretsError",
    "UsageError",
    "ValidationError",
]
